book_initial_y = ob_recipe_book.y;
x_origin = 96;
x_offset = 16;
combo = ob_control.combo;
cam_y = 0;
glide = 0;
cam = view_camera[0];
room_height = 24 + ob_control.max_num*63;
setUIHeight(ob_null);
setUIHeight(ob_mix_area);